apiVersion: apps/v1
kind: Deployment
metadata:
  name: go_hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go_hello
  template:
    metadata:
      labels:
        app: go_hello
    spec:
      containers:
      - name: go_hello
        image: swim0000/go_hello:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
